#ifndef SHADOW_FILTER_MODES_H
#define SHADOW_FILTER_MODES_H

#define SHADOW_FILTERING_NONE 0
#define SHADOW_FILTERING_HARDWARE_PCF 1
#define SHADOW_FILTERING_PCF_3x3 2
#define SHADOW_FILTERING_PCF_TENT_3x3 3
#define SHADOW_FILTERING_PCF_TENT_5x5 4

#endif
