#ifndef SAMPLERS_HLSLI
#define SAMPLERS_HLSLI

#include "ShaderInterop.h"

SAMPLERCOMPARISONSTATE(gSamplerCmpPcf, SAMPLER_SLOT_CMP_PCF);
SAMPLERCOMPARISONSTATE(gSamplerCmpPoint, SAMPLER_SLOT_CMP_POINT);

SAMPLERSTATE(gSamplerAf16, SAMPLER_SLOT_AF16);
SAMPLERSTATE(gSamplerAf8, SAMPLER_SLOT_AF8);
SAMPLERSTATE(gSamplerAf4, SAMPLER_SLOT_AF4);
SAMPLERSTATE(gSamplerTri, SAMPLER_SLOT_TRI);
SAMPLERSTATE(gSamplerBi, SAMPLER_SLOT_BI);
SAMPLERSTATE(gSamplerPoint, SAMPLER_SLOT_POINT);

#endif